name: syncfusion_flutter_gauges
description: The Flutter gauges library includes a linear gauge and radial gauge (a.k.a. circular gauge) to create modern, interactive, animated gauges and radial sliders.
version: 18.3.35
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_gauges

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    git:
      url: https://github.com/fodil-a/flutter-widgets.git
      path: ./packages/syncfusion_flutter_core
      ref: master
  intl: ^0.17.0

flutter:
 
